"use client";

import { useEffect, useRef, useState } from "react";
import { flushSync } from "react-dom";
import { ArrowUpRight, ArrowDown, Plus, Menu, Check } from "lucide-react";
import ProjectInquiry, { ColorField } from "@/components/prosurface/project-inquiry";
import { CourtStudio, OpeningFilm, PremiumMotion, ReplayFilm } from "@/components/prosurface/court-experience";
import { ProjectGallery, collection } from "@/components/prosurface/project-gallery";
import { LocalDetails } from "@/components/prosurface/local-details";
import { BeforeAfter } from "@/components/prosurface/before-after";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Dialog, DialogContent, DialogDescription, DialogTitle } from "@/components/ui/dialog";

const palettes=[{name:"Pro blue",base:"#1045ab",key:"#058fce",surround:"#8e999d"},{name:"Woodland",base:"#28583e",key:"#bc7450",surround:"#b5a286"},{name:"After hours",base:"#34334e",key:"#918779",surround:"#595d60"},{name:"Home team",base:"#35213f",key:"#e1ab23",surround:"#d5a325"}];
const projects=collection.slice(0,3);
function Brand(){return <a className="brand" href="#top" aria-label="ProSurface home"><span className="logo-crop"><img src="/images/logo.jpg" alt=""/></span><span>PROSURFACE<small>PERFORMANCE COURTS</small></span></a>}
export default function Home(){
 const [palette,setPalette]=useState(0);const [sport,setSport]=useState("Multi-sport");const [inquiry,setInquiry]=useState(false);const [menu,setMenu]=useState(false);const [project,setProject]=useState<number|null>(null);const [message,setMessage]=useState("");const heroRef=useRef<HTMLDivElement>(null);const galleryOrigin=useRef<HTMLElement|null>(null);
 const [custom,setCustom]=useState({...palettes[0],name:"Custom"});const activePalette=palette===palettes.length?custom:palettes[palette];
 useEffect(()=>{const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add("revealed");observer.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll(".reveal").forEach(el=>observer.observe(el));return()=>observer.disconnect()},[]);
 useEffect(()=>{const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>|void}}).modelContext;if(!context)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:"configure_court_preview",description:"Set the visible court concept's sport and palette. This only changes the preview and does not contact ProSurface.",inputSchema:{type:"object",properties:{sport:{type:"string",enum:["Basketball","Pickleball","Multi-sport"]},palette:{type:"string",enum:palettes.map(p=>p.name)}},required:["sport","palette"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(input:unknown)=>{const value=input as {sport:string;palette:string};const index=palettes.findIndex(p=>p.name===value?.palette);if(!value||!["Basketball","Pickleball","Multi-sport"].includes(value.sport)||index<0)throw new Error("Choose a listed sport and palette.");flushSync(()=>{setSport(value.sport);setPalette(index)});return {sport:value.sport,palette:value.palette,status:"preview_updated"}}},{signal:lifecycle.signal})).catch(()=>{})}catch{}return()=>lifecycle.abort()},[]);
 return <><OpeningFilm/><PremiumMotion/><main id="top">
 <a className="skip" href="#work">Skip to content</a><header className="nav"><Brand/><nav aria-label="Main navigation"><a href="#work">Our work</a><a href="#surfaces">Our surfaces</a><a href="#design">Your court</a></nav><button className="nav-cta" onClick={()=>setInquiry(true)}>Let’s talk courts <ArrowUpRight size={17}/></button><button className="menu-button" aria-label="Open navigation" onClick={()=>setMenu(true)}><Menu/></button></header>
 <section className="hero"><div className="hero-top"><span className="eyebrow">PRECISION UNDERFOOT. POSSIBILITY AHEAD.</span><span className="hero-locale">DALLAS–FORT WORTH & BEYOND</span></div><h1>HOME COURT.<br/><span>UNFAIR ADVANTAGE.</span></h1><div className="hero-image" ref={heroRef}><img src="/images/blue-court.jpg" fetchPriority="high" width="590" height="332" alt="Blue ProSurface basketball and pickleball court viewed from above"/><div className="image-shade"/><div className="hero-copy"><p>The place everyone wants to play.<br/>Built around you. Built by ProSurface.</p><a className="button light" href="#design">Experience your court <ArrowUpRight size={20}/></a><ReplayFilm/></div><span className="hero-index">THE POSSIBILITIES START HERE</span><a className="scroll-link" href="#work" aria-label="Explore our work"><ArrowDown size={23}/></a></div></section>
 <div className="credentials"><span><Check size={16}/> Certified SportMaster installer</span><span>ATHLETIC COURTS</span><span>SPECIALTY COATINGS</span><span>DFW & BEYOND</span></div>
 <section id="work" className="intro reveal"><span className="eyebrow">THE PROSURFACE COLLECTION</span><h2>Make room<br/>for <em>more play.</em></h2><div><p>The early-morning shootaround. The one-more-game evenings. The backyard everyone ends up in.</p><p>We build and resurface athletic courts that make your space a destination. Your game. Your colors. Your home court.</p><a className="text-link" href="#design">Imagine your court <ArrowUpRight size={18}/></a></div></section>
 <section className="projects" aria-label="Selected ProSurface projects">{projects.map((p,i)=><button key={p.name} className={`project-card project-${i} reveal`} onClick={event=>{galleryOrigin.current=event.currentTarget;setProject(i)}}><div className="project-image"><img src={`/images/${p.image}`} loading="lazy" width="590" height={i===0?332:443} alt={p.description}/><span className="project-view">EXPLORE THE SPACE <ArrowUpRight size={19}/></span><span className="photo-index">{["THE SIGNATURE","THE RETREAT","THE STATEMENT"][i]}</span></div><div className="project-caption"><h3>{p.name}</h3><span>{p.type}</span></div></button>)}<div className="collection-invite"><span>COURTS. COATINGS. POSSIBILITIES.</span><button className="text-link" onClick={event=>{galleryOrigin.current=event.currentTarget;setProject(0)}}>Explore the full collection <ArrowUpRight size={18}/></button></div></section>
 <section id="design" className="designer"><div className="designer-heading reveal"><span className="eyebrow">THE COURT, REIMAGINED</span><h2>Your court.<br/><em>Your signature.</em></h2><p>Start with a game. Find your colors.<br/>Then let’s bring it to your backyard.</p></div><CourtStudio palette={activePalette} sport={sport}/><div className="design-controls"><div><label className="control-label" id="sport-label">YOUR GAME</label><RadioGroup value={sport} onValueChange={setSport} aria-labelledby="sport-label" className="sport-options">{["Basketball","Pickleball","Multi-sport"].map(s=><label key={s} className={sport===s?"sport-option active":"sport-option"}><RadioGroupItem value={s}/><span>{s}</span></label>)}</RadioGroup></div><div><label className="control-label" id="palette-label">YOUR PALETTE</label><RadioGroup value={String(palette)} onValueChange={v=>setPalette(Number(v))} aria-labelledby="palette-label" className="palette-options">{[...palettes,custom].map((p,i)=><label key={p.name} className={`palette ${palette===i?"selected":""}`}><RadioGroupItem value={String(i)} aria-label={p.name}/><span className="swatch" style={{background:`linear-gradient(135deg,${p.base} 50%,${p.key} 50%)`}}/><span>{p.name}</span></label>)}</RadioGroup></div><button className="button blue" onClick={()=>setInquiry(true)}>Let’s build this <ArrowUpRight size={20}/></button>{palette===palettes.length&&<div className="custom-colors"><div className="custom-colors-heading"><span>YOUR COLORS. NO COMPROMISE.</span><p>Choose a color or enter a hex code.</p></div>{([["base","Playing surface"],["key","Key / accent"],["surround","Surround"]] as const).map(([key,label])=><ColorField key={key} label={label} value={custom[key]} onChange={value=>setCustom(p=>({...p,[key]:value}))}/>)}</div>}</div><p className="concept-note">Explore the feel. Make it your own. This 3D concept is illustrative; final colors, layout, and dimensions are tailored to your property.</p></section>
 <section id="surfaces" className="surfaces"><div className="surface-intro reveal"><span className="eyebrow">CRAFT / FROM THE GROUND UP</span><h2>Good looks.<br/><em>Serious game.</em></h2><p>Whether you’re starting fresh or bringing a favorite space back to life, the finish makes all the difference.</p><div className="cert"><Check size={22}/><div>Certified SportMaster installer<small>A specialist behind your playing surface.</small></div></div></div><div className="services reveal">{[{title:"Athletic court construction",copy:"A dedicated place for basketball, pickleball, tennis, and more. Let’s plan a court around your property and the way you want to play.",tags:"BASKETBALL / PICKLEBALL / TENNIS"},{title:"Court resurfacing",copy:"Give your existing court a new chapter. Talk with us about its current condition, your color direction, and a surface made for getting back in the game.",tags:"REFRESH / RECOLOR / RESTRIPE"},{title:"Specialty epoxy coatings",copy:"From residential spaces to aircraft hangars, a seamless finish changes the entire room. Explore a look that fits your space and how you use it.",tags:"RESIDENTIAL / COMMERCIAL / HANGARS"},{title:"Stained & sealed concrete",copy:"Bring out the character of your concrete with a considered stain and sealed finish. Start with the surface you have; make it something you love.",tags:"COLOR / CHARACTER / FINISH"}].map((s,i)=><details key={s.title} open={i===0?true:undefined}><summary><span className="service-symbol" aria-hidden="true">{["↗","↻","◈","≋"][i]}</span><h3>{s.title}</h3><Plus size={23}/></summary><div className="service-content"><p>{s.copy}</p><span>{s.tags}</span></div></details>)}</div></section>
 <section className="transformation"><div className="transform-heading reveal"><div><span className="eyebrow">BEYOND THE BASELINE</span><h2>Same space.<br/><em>Whole new feeling.</em></h2></div><p>Our craft goes beyond courts.<br/>See what a specialty coating can do.</p></div><BeforeAfter/><div className="hangar reveal"><img src="/images/hangar.jpg" alt="Red, black, and gray coated floor in an aircraft hangar" loading="lazy" width="590" height="443"/><div><span className="eyebrow">FROM THE BACKYARD TO THE HANGAR</span><h3>No ordinary<br/>surface.</h3><p>For spaces with a purpose.<br/>And owners with a vision.</p><button className="text-link" onClick={()=>{setMessage("I'd also like to discuss specialty coatings.");setInquiry(true)}}>Talk specialty finishes <ArrowUpRight size={18}/></button></div></div></section>
 <section className="process reveal"><div><span className="eyebrow">FROM FIRST IDEA TO FIRST GAME</span><h2>Let’s get<br/><em>you playing.</em></h2></div><div className="steps"><article><span className="step-word">ENVISION</span><h3>Tell us your vision.</h3><p>Your space, your sports, your wish list. A conversation is the best place to start.</p></article><article><span className="step-word">REFINE</span><h3>Find your fit.</h3><p>Talk through the site, surface, layout, and colors with the ProSurface team.</p></article><article><span className="step-word">PLAY</span><h3>Make it yours.</h3><p>Turn the plan into a space you can’t wait to step onto.</p></article></div></section>
 <LocalDetails/>
 <section id="contact" className="contact"><div className="contact-top"><span className="eyebrow">YOUR NEXT GREAT GAME STARTS HERE.</span><span>DFW & BEYOND</span></div><h2>THE BEST SEAT<br/>IS <em>ON YOUR COURT.</em></h2><div className="contact-bottom"><button className="button light" onClick={()=>setInquiry(true)}>Let’s create your court <ArrowUpRight size={21}/></button><a href="tel:+19037327124">Or call us directly<br/><strong>(903) 732-7124</strong></a></div></section>
 <footer><Brand/><p>Athletic courts. Exceptional surfaces.<br/>Dallas–Fort Worth & beyond.</p><a href="#top">BACK TO TOP ↑</a><div className="footer-bottom"><span>© {new Date().getFullYear()} ProSurface Performance Courts</span><ReplayFilm/><span>BUILT FOR THE WAY YOU PLAY.</span></div></footer>
 <ProjectInquiry open={inquiry} onOpenChange={setInquiry} palette={activePalette} sport={sport} initialMessage={message}/>
 <ProjectGallery index={project} onIndexChange={setProject} restoreFocus={()=>galleryOrigin.current?.focus({preventScroll:true})} onInquiry={()=>{setProject(null);setInquiry(true)}}/>
 <Dialog open={menu} onOpenChange={setMenu}><DialogContent className="mobile-menu"><DialogTitle>Explore ProSurface</DialogTitle><DialogDescription>Find your home-court advantage.</DialogDescription>{[["Our work","work"],["Our surfaces","surfaces"],["Your court","design"]].map(([label,id])=><a key={id} href={`#${id}`} onClick={()=>setMenu(false)}>{label}<ArrowUpRight/></a>)}<a href="tel:+19037327124">(903) 732-7124</a></DialogContent></Dialog>
 </main></>
}
